---

- name: Moving the file map.yaml to ansible
  copy:
    src: "{{ lookup('env','JENKINS_HOME') }}/jobs/{{ lookup('env','JOB_NAME') }}/builds/{{ lookup('env','BUILD_NUMBER') }}/archive/build/src/serialize"
    dest: "/home/qb/serializer_{{ lookup('env','BUILD_NUMBER') }}"
    mode: 0644
- name: Looking up the build tag etc
  debug: msg="{{ lookup('env','BUILD_TAG') }}"